### PR TITLE
Extend taxonomy options

### PR DESCRIPTION
**Pull request by philcable**
Initial work to for https://github.com/happyprime/latest-custom-posts/issues/10.

Not 100% there just yet, but usable to some extent :)

I don't know if `'relation' => 'AND'` queries or use of the `operator` argument for finding posts with all the given terms are supported by WPAPI, so accurate results won't be reflected in the editor if those are used. The front end should work as expected, though. Other than that, there are very likely a few other wrinkles on the editor side that need to be ironed out.

### CODE REVIEW

**Comment by philcable** [comment]
Getting into reasonably decent shape. There's still a conflict that occurs if a page has more than one instance of the block and both are using multiple taxonomy settings, where the terms for one selected taxonomy will show up as options for a different selected taxonomy.

**Comment by slocker3** [comment]
@philcable I have found an additional issue. Here are the current issues:

- [ ] LCT term takes on term for last instance of LCT on page
- [ ] If no taxonomy is selected no posts show up on frontend. Admin displays as expected

**Comment by philcable** [comment]
@slocker3 I think those last few commits (finally!) fix the two issues you pointed out.

**Comment by philcable** [comment]
Alright - with the last few commits, this should now be back-compatible!

**Comment by philcable** [comment]
This will also fix https://github.com/happyprime/latest-custom-posts/issues/13.

**Pull request merged**
